### ISSUE TITLE
Room.getTerrain() seems to be missing 

### ISSUE THREAD

**Issue by tcdejong** [screepers/typed-screeps#104]
### Expected Behavior

Room.getTerrain() returning a Room.Terrain object

### Actual Behavior

`Property 'getTerrain' does not exist on type 'Room'`

### Sample code (if available)

```ts
  const thisRoom = Game.spawns.Spawn1.room;
  const terrain = thisRoom.getTerrain();
```

### Your Environment

- Node.js version: V8 / 6.1.534.50 (I hope that's the right one)
- TypeScript version: 3.1.1
- `@types/screeps` version: 2.5.1

**Comment by tcdejong** [comment]
It's in this repo, but somehow not installing right. https://github.com/screepers/typed-screeps/blob/master/dist/index.d.ts#L3202

Either way, this seems to be on my end.

**Comment by Jomik** [comment]
This is because this repo has not been merged into @types/screeps yet. You should be fine leaving this issue open.

**Comment by riggs** [comment]
It has since been updated, so go ahead and close it, again ;-)

**Comment by kotarou** [comment]
As requested.
