### ISSUE TITLE
Feature: Add types for Power Creeps release

### ISSUE THREAD

**Issue by pyrodogg** [screepers/typed-screeps#117]
### Expected Behavior

Power Creeps are currently available on PTR and are expected to be released on MMO [on March 18th](https://twitter.com/ScreepsGame/status/1106266747995385857). Types for the Power Creeps entities should be added or updated.

- Game.gpl - [ptr](https://ptr-docs.screeps.com/api/#Game.gpl)
  - New
- Game.powerCreeps - [ptr](https://ptr-docs.screeps.com/api/#PowerCreep.name)
  - New
- ~~Game.spawns - [ptr](https://ptr-docs.screeps.com/api/#Game.spawns)~~
  - ~~May contain `StructureSpawn` and `StructurePowerSpawn` entities?~~
  - PowerSpawns are not available in `Game.spawns` and there is no corresponding `Game.powerSpawns`.
- InterShardMemory - [ptr](https://ptr-docs.screeps.com/api/#InterShardMemory)
  - Also expected to launch with Power Creeps
- Memory.powerCreeps - [ptr](https://ptr-docs.screeps.com/api/#PowerCreep.memory)
  - New
- PowerCreep - [ptr](https://ptr-docs.screeps.com/api/#PowerCreep)
  - New
- StructurePowerSpawn - [ptr](https://ptr-docs.screeps.com/api/#StructurePowerSpawn)
  - Exists but `createPowerCreep` should be removed

**Comment by o4kapuk** [comment]
As far as I remember, Power Creeps are in their own object Game.powerCreeps, not mixed with regular ones in Game.creeps. Same to FIND_* and LOOK_* things, they all are separate

**Comment by pyrodogg** [comment]
Good to know. I was just starting to look at it to get an idea for what needed changing. The PTR api docs don't fully specify Game.powerCreeps but it looks like it's mentioned in the PowerCreep section. Same with Memory.powerCreeps. Will update the issue description

**Comment by kamotswind** [comment]
Game.spawns will not contain StructurePowerSpawn entities.

**Comment by kotarou** [comment]
Closing, as solved in 2.4.5
