### ISSUE TITLE
findClosestByRange(FIND_MY_STRUCTURES filter does not allow STRUCTURE_CONTAINER

### ISSUE THREAD

**Issue by thmsndk** [screepers/typed-screeps#121]
It would appear that STRUCTURE_CONTAINER is not considered a owned structure type

### Expected Behavior
using `creep.pos.findClosestByRange(FIND_MY_STRUCTURES` allows for the structure.structureType to be of the type STRUCTURE_CONTAINER

### Actual Behavior

using `creep.pos.findClosestByRange(FIND_MY_STRUCTURES` does not allow for the structure.structureType to be of the type STRUCTURE_CONTAINER

TypeScript complains about AnyOwnedStructure not containing StructureContainer making the sample code invalid

### Sample code (if available)

```ts
const target = creep.pos.findClosestByRange(FIND_MY_STRUCTURES, {
        filter: structure => {
          switch (structure.structureType) {
            case STRUCTURE_CONTAINER: // the compiler throws an error about this line
              const container = structure as StructureContainer
              return _.sum(container.store) < container.storeCapacity && haulers.length > 0
          }

          return false
        }
      })
```

Adding this to index.d.ts makes the compiler happy
```
type AnyOwnedStructure =
  | StructureContainer
...
```

### Your Environment

- Node.js version: 12.3.1
- TypeScript version: 2.9.2
- `@types/screeps` version: 2.5.4

**Comment by thmsndk** [comment]
Apparently, StructureContainer is not owned by anyone

**Comment by kotarou** [comment]
Yea, [StructureContainer](https://docs.screeps.com/api/#StructureContainer) does not inherit from OwnedStructure.

**Comment by DollarAkshay** [comment]
Was about to create an issue for this. Damn, thats really weird to have Containers that is not owned by anyone.
