### ISSUE TITLE
Ruins

### ISSUE THREAD

**Issue by pyrodogg** [screepers/typed-screeps#126]
### Brief Description

- [x] Implement [`Ruin`](https://docs.screeps.com/api/#Ruin) game object type

When structures are destroyed, they drop a ruin object (similar to tombstones for creeps) which will contain all of the structures resources.

### Reference to Screeps Changelog (if available)

[Factories, new resources, NPC Strongholds](https://screeps.com/forum/topic/2814/factories-new-resources-npc-strongholds/2)

<!--### Sample code (if available)

```ts
// Please include your code within this block.
```-->

**Comment by pyrodogg** [comment]
Also covered by #132

**Comment by kotarou** [comment]
Fixes now merged.
