### ISSUE TITLE
Unexpected type when trying to get specific structure from 'AnyStructure'

### ISSUE THREAD

**Issue by walze** [screepers/typed-screeps#136]
Shouldn't `asd2` be of type `123` as well? since AnyStructure has `StructureSpawn` in its union?

```ts
type asd = StructureSpawn['structureType'] extends STRUCTURE_SPAWN ? 123 : never // asd is 123 as expected
type asd2 = AnyStructure['structureType'] extends STRUCTURE_SPAWN ? 123 : never // asd2 is never ??? why
```

What i'm trying to do is something like `Structure<STRUCTURE_SPAWN>` and get the type `StructureSpawn`. If you think of something else to do this behaviour, please let me know c:

**Comment by pyrodogg** [comment]
Could you provide a more inclusive example of what you're trying to do?

AnyStructure['structureType'] doesn't extend STRUCTURE_SPAWN because it could also be any other structure type string literal.

```
type asd2 = AnyStructure['structureType'] extends string ? 123 : never // asd is 123 as expected
```

**Comment by walze** [comment]
> Could you provide a more inclusive example of what you're trying to do?
> 
> AnyStructure['structureType'] doesn't extend STRUCTURE_SPAWN because it could also be any other structure type string literal.

Basically, i have a `findStructure` function and i want it to return the structure class
Right now, my current temporary solution is doing like

```ts
type Structures = {
  [STRUCTURE_CONTAINER]: StructureContainer
  [STRUCTURE_CONTROLLER]: StructureController
  [STRUCTURE_EXTENSION]: StructureExtension
}

let container: Structures[STRUCTURE_CONTAINER] // this will be of type 'StructureContainer'
```
