### ISSUE TITLE
Game.cpu.halt() missing

### ISSUE THREAD

**Issue by tcdejong** [screepers/typed-screeps#140]
### Brief Description

`Game.cpu.halt()` is missing from the type declarations. I'm not entirely sure how type type it, because it interrupts script execution and thus might cause unreachable code as well.

### Reference to Screeps Changelog (if available)

https://blog.screeps.com/2018/12/changelog-2018-12-14/ (bottom, under "other changes")
https://docs.screeps.com/api/#Game.halt

### Sample code (if available)

Potential usage: force a global reset if we just respawned. 
```ts
// Check if we just respawned
if (hasRespawned()) {
    // wipe memory
    Memory = { };
    // force global reset
    Game.cpu.halt()
}
```

Typing:
```ts

interface CPU {
    // ... existing entries...
    /**
     * Reset your runtime environment and wipe all data in heap memory.
     */
    halt(): void;
}
```

As mentioned in the description, I'm not sure if the code interruption can be included in the typings.

**Comment by pyrodogg** [comment]
I just did a quick test on my private server. Player code execution is stopped immediately, so I thought `never` might be a better type than `void` but I don't see any difference to linting in VS Code. 

ex. This doesn't get flagged as invalid

```ts
interface CPU{
  halt(): never;
}
...
shootFoot(): void {
  Game.cpu.halt(); // Execution stops here
  console.log("Got past halt!"); // Never executed
}
```

I think `never` might be better though since it reflects that the function has an "unreachable endpoint" and execution is not returned to the calling code.

Please implement conditionally similar to `getHeapStatistics`, since it only exists in IVM environments. Otherwise, give a shout and I can follow-up on it.

**Comment by tcdejong** [comment]
I believe opting out of IVM is no longer possible. The option is not visible in my "manage account" settings, and it was enabled by default for new users here: https://blog.screeps.com/2018/08/world-review/#Isolated-VM

**Comment by tcdejong** [comment]
Updating TS to 3.7 also causes the unreachable code to work as desired when typing as `never`.

```ts
interface CPU {
  halt(): never;
}

function shootAndMiss() {
  Game.cpu.halt() // Execution stops here
  console.log("Hello?") // ts(7027) unreachable code detected
}
```

```ts
interface CPU {
  halt(): void;
}

function shootFoot() {
  Game.cpu.halt() // Execution stops here
  console.log("Hello?") // no error
}
```

However, this introduces another problem (using shootFoot from above, without `:void`) :

```ts

function whatsRunning() {
  console.log("I'm alive") // no warnings
  shootFoot(); // Execution stops here - typed as `void`, should be `never`
  console.log("Or am I?") // No warning, shootFoot typed as void. However, should be unreachable.
}
```

**Comment by pyrodogg** [comment]
So yes, the type should be `halt(): never`. The min TS version of this library doesn't need to change. Users get the benefit of 3.7 validation if they use it in their own project.

It looks like the IVM setting is hidden but still accessible. 
https://screeps.com/a/#!/account/runtime
_(as linked from https://docs.screeps.com/api/#Game.halt)_
