### ISSUE TITLE
Push 3.0 Update to DT

### ISSUE THREAD

**Issue by pyrodogg** [screepers/typed-screeps#148]
Things are finally settling down enough that I'm planning to push the 3.0 update to Definitely Typed Saturday November 23rd. 

## Update checklist

If you are just submitting a PR, this isn't needed, but for new maintainers, when preparing a new version or updates:

1. Update the changelog with links to each relevant PR
2. Update the contributors list.
3. Update version numbers if required
4. (If releasing) Package a release / Update the relevant draft release
5. Close / Update relevant issues
6. (If publishing) Submit a PR to Definitely-Typed

**Comment by Arcath** [comment]
All sounds good to me!

Sorry I've been quiet over all these big changes, I've been reading the notification emails but I'm that busy I don't have time to play screeps or help out with the typings.

**Comment by pyrodogg** [comment]
PR submitted to DefinitelyTyped to publish v3.0.0

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40613

**Comment by pyrodogg** [comment]
After some additional updates version v3.0.1 has been accepted to DefinitelyTyped. NPM is now serving updates at `@types/screeps`
