### ISSUE TITLE
Figure out how to make typings publishable on DT

### ISSUE THREAD

**Issue by resir014** [screepers/typed-screeps#15]
The current `npm` installation method is fine, but it would be better if we could publish the typings to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) so we could easily install it with `@types/`, without altering the `tsconfig` further.

Putting this as a reminder for upcoming release.

**Comment by apemanzilla** [comment]
(Mostly copied from discussions on Slack) I think there are two ways we could do this. The first way (the easier way) would be to keep the project as-is, and then push the compiled `screeps.d.ts` file to DefinitelyTyped. It might have to be reformatted some to match their requirements, but it would keep things simple. The other option would be to rewrite the definitions as `.d.ts` files, using triple-slash references to link them, and then pushing all of them (including an `index.d.ts`) to DefinitelyTyped. It _should_ be relatively straightforward to port the current sources to definitions (pretty much just adding `declare` keywords).

I think the first method (keeping it as-is and pushing the compiled definitions) is the better way, but what do you guys think?

**Comment by resir014** [comment]
@apemanzilla I would be fine either way. I'm going to run a PR tonight that will restructure the project in a way that won't divert too far from the first method, so let's try that first.

**Comment by resir014** [comment]
Should be fixed with #20. We'll copy over the built files of each version + test files to the DT repo.
