### ISSUE TITLE
StructureController.owner can be undefined

### ISSUE THREAD

**Issue by pathurs** [screepers/typed-screeps#159]
### Expected Behavior

```
interface StructureController {
    owner: Owner | undefined;
}
```

### Actual Behavior

`StructureController` extends `OwnedStructure` which has `owner` property always defined.

**Comment by screeps-qnz** [comment]
it might be that way because it works that way in the engine code: https://github.com/screeps/engine/blob/master/src/game/structures.js#L171

**Comment by pyrodogg** [comment]
Both the engine code linked by qnz and also the Screeps [docs](https://docs.screeps.com/api/#StructureController.owner) show StructureController to extend OwnedStructure.

If this isn't the behavior in game, I'd suggest first submitting an issue on Screeps/engine.

**Comment by pathurs** [comment]
This is incorrect, the engine code states it can be undefined: https://github.com/screeps/engine/blob/592c80b9a71960c13bc93971595c62112d8f1406/src/game/structures.js#L136

**Comment by pyrodogg** [comment]
@pathurs Please see a possible solution in the associated PR. Review and testing comments welcome.
