### ISSUE TITLE
FindPathOpts.costCallback should return void|CostMatrix

### ISSUE THREAD

**Issue by mnpenner** [screepers/typed-screeps#167]
[The docs](https://docs.screeps.com/api/#Room.findPath) aren't totally clear about what you should return if you don't return a CostMatrix, but returning nothing seems to work fine. Right now it's tagged as:

```
costCallback?(roomName: string, costMatrix: CostMatrix): boolean | CostMatrix;
```

I don't know what this boolean is. Returning `true` or `false` doesn't seem to make a difference. I think it should be `void|CostMatrix`

**Comment by pyrodogg** [comment]
Yea, `void | CostMatrix` seems more correct upon looking at the current [intent code](https://github.com/screeps/engine/blob/5eec8a935db9715845ec5bdad1249fd9b8fe8e3d/src/game/rooms.js#L243..L253). 

Digging into this repo history all I can find is that it apparently used to allow skipping rooms by returning false but that behavior seems to have changed some years ago.

**Comment by pyrodogg** [comment]
Apparently `Pathfinder.search` callback allows returning false to skip room. However this is typed separately. It looks like there is a [PR](https://github.com/screeps/engine/pull/113) on the screeps engine to allow similar functionality on `FindPathOpts` but it requires review.

**Comment by mnpenner** [comment]
Well, it wouldn't be hard to change it to `void|false|CostMatrix` if that gets merged in. `FindPathOpts` still needs to be split in two though I guess.
