### ISSUE TITLE
Potential solution for store/carry current Caveat

### ISSUE THREAD

**Issue by Varatnar** [screepers/typed-screeps#173]
There is a mention of the store being a list of optional keys for all resource but the energy key is always there. 

Something like below would make the type behave has what i understood from the caveat description. By using the helper type `Omit` (typescript 3.5+) it is somewhat trivial to cherry pick attributes. Note that to test this i changed the type of the `Store` interface to have all its key optional.
```ts
interface StructureContainer extends Structure<STRUCTURE_CONTAINER> {
    (...)
    store: GuaranteedEnergy;
    (...)
}

type GuaranteedEnergy = FlipResourceToMandatory<Store<ResourceConstant, false>, RESOURCE_ENERGY>;

type FlipResourceToMandatory<FULL_KEYS, KEY_TO_FLIP extends keyof any> = Omit<FULL_KEYS, KEY_TO_FLIP> & { [R in KEY_TO_FLIP]: number};

type Store<POSSIBLE_RESOURCES extends ResourceConstant, UNLIMITED_STORE extends boolean> = StoreBase<POSSIBLE_RESOURCES, UNLIMITED_STORE> &
    { [P in POSSIBLE_RESOURCES]?: number } &  // <--- set to optional for example
    { [P in Exclude<ResourceConstant, POSSIBLE_RESOURCES>]: 0 };
```

Assuming the project does not wish to move to a more recent version of typescript, the `Omit` helper type could simply be defined locally. Below is their implementation.

```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

I could attempt a PR if this is indeed the wanted behavior.

**Comment by pyrodogg** [comment]
I'm not sure this is really the case any more with `Store`. It doesn't seem to have any special logic for energy, behaves the same for all resources.

https://github.com/screeps/engine/blob/master/src/game/store.js

**Comment by Varatnar** [comment]
If it is indeed not an issue anymore i highly suggest removing the caveats from the Readme (and closing this issue)
