### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by pyrodogg** [screepers/typed-screeps#185]
Travis CI is changing how they support OSS projects, migrating them from travis-ci.org to travis-ci.com, where the commercial plans are operated. [1]  OSS projects would need to continually apply for a pool of credits in order to continue getting free build time. [2]

For the trivial compile checking of this project, using Github actions would be much simpler, and avoids extra paperwork. travis-ci.org goes read-only after December 31, 2020.

[1] https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/
[2] https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only

**Comment by DiamondMofeng** [comment]
Added github action in #232. Currently just simply build then run lint&dtslint tests.
