### ISSUE TITLE
Season 1

### ISSUE THREAD

**Issue by pyrodogg** [screepers/typed-screeps#187]
Screeps has introduced the concept of [seasonal worlds](https://twitter.com/ScreepsGame/status/1329440931876139019) which run for a set period of time and provide a different API from MMO/pserver. 

Season API docs now published: https://docs-season.screeps.com/api
 ~~The full Game API will not be known until ticks start, but~~ some information can already be gathered from [external APIs](https://screeps.com/season/api/game/room-objects?shard=shardSeason&room=W7S1) and the announcement thread on the forum. 

Since the seasons are expected to be substantially different from MMO, with changes to or removal of existing structures, it's looking like the best option is to have a separate branch that is maintained for seasonal changes, separate from MMO.

Users would be able to either add the new branch from this repo as a project dependency, or we could eventually consider publishing to something like `@types/screeps-seasonal` at DefinitelyTyped. If players are using branched source control, they can reasonably support different dependencies for different branches. This would be less convenient for users preferring to support mmo/pserv and seasonal from a single codebase w/ single set of dependencies. 

Since this is an community project and we're not party to designing the API, I'm reluctant to try making this any more "composable" (ex.having mmo and seasonal, both dependent on a core library). The amount of unknown refactoring that can't be planned for outweighs the effort in maintaining two separate branches.

The alternative to separate branches is to have a "merge" of both distinct APIs somehow reflected in the main branch, which doesn't reflect well on mmo/pserv (where slight variations already exist), or seasonal. Season 1 was initially supposed to remove terminals entirely (since reversed). In a merged branch such a removal could not be reflected for seasonal.

#### Game API (DRAFT - API not fully published yet)
- ~~STRUCTURE_SCORE_CONTAINER~~
- ~~STRUCTURE_SCORE_COLLECTOR~~
- Confirmed constants
```
Object.assign(exports, {
    RESOURCE_SCORE: 'score',
    FIND_SCORE_CONTAINERS: 10011,
    FIND_SCORE_COLLECTORS: 10012,
    WALLS_RADIUS: 5,
    SCORE_CONTAINER_SPAWN_CHANCE: 0.01,
    SCORE_CONTAINER_SPAWN_INTERVAL: 500,
    SCORE_COLLECTOR_SINK: 20,
    SCORE_COLLECTOR_MAX_CAPACITY: 20000
};
```

#### Repository
- New `season` branch
- Updates to Readme to reflect new structure

**Comment by Joppe-A** [comment]
I have no plans to join seasons, I would prefer to keep it out of my typings. Having an additional separate seasons definition file seems viable for season 1 as it only adds a few things. I'd suggest starting there (a separate repo with only the additions, v1 = seasons 1). 

Even if season 2 has no terminals most people would probably still prefer to have a definition of say _StructureTerminal_ so people can carry their code from season to season and share parts of it with MMO server. Capability flagging is probably something people prefer over having all these compile errors suddenly after updating the definitions for a new season.
