### ISSUE TITLE
season2 SymbolDecoder

### ISSUE THREAD

**Issue by bastianh** [screepers/typed-screeps#191]
### Expected Behavior

`SymbolDecoder` should be useable with `instanceof` 

### Actual Behavior

TS2693: 'SymbolDecoder' only refers to a type, but is being used as a value here.

### Your Environment

- Node.js version: 10.23.0
- TypeScript version: 4.2.3
-  screepers/typed-screeps#season-2

**Comment by pyrodogg** [comment]
Thanks. I missed the constructor types for the new symbol objects. I added a test, it should be working now on the `season-2` branch.
