### ISSUE TITLE
`Spawning.directions` can be undefined

### ISSUE THREAD

**Issue by tiennou** [screepers/typed-screeps#243]
Playing around with spawns, I believe there's an error in the typedefs:

```ts
interface Spawning {
    directions: DirectionConstant[];
}
```

I got an error accessing `.length` on that, which makes me think that unless you're explicitly setting `SpawnOptions.directions`, or are using `Spawning.setDirections` once spawning starts, this will return `null`/`undefined` while the creep will actually default to `[TOP]`.

**Comment by DiamondMofeng** [comment]
Yes. I just confirmed that it is an optional property. 
Would you like to create a pull request to fix this? 

Anyway, these changes won't be released to npm anytime soon, so you may need to manually install the package from github like `npm i https://github.com/screepers/typed-screeps`. Notice: there is a breaking change about Game.getObjectById
