### ISSUE TITLE
add _bits to CostMatrix

### ISSUE THREAD

**Issue by CarsonBurke** [screepers/typed-screeps#248]
CostMatrix currently doesn't include the readable and writable _bits property used to store coord data. It probably should.

```ts
interface CostMatrix {
    _bits: Uint8Array
}
```

**Comment by sparr** [comment]
This doesn't appear to be implemented.

https://github.com/screepers/typed-screeps/blob/master/dist/index.d.ts#L3900-L3922

**Comment by CarsonBurke** [comment]
@sparr I agree I'm not sure why I closed this.
