### ISSUE TITLE
typed-screeps 2.0 does not allow for modification of the `Game` interface

### ISSUE THREAD

**Issue by bencbartlett** [screepers/typed-screeps#26]
I do a lot of per-tick caching on a `Game.cache` object. Modifying the `Game` interface results in the error `TS2451: Cannot redeclare block-scoped variable 'Game'.`:

![image](https://user-images.githubusercontent.com/6800253/34075158-e682e9aa-e272-11e7-81e2-602e0dd802ad.png)

However, if I change line 981 of the screeps.d.ts file of typed-screeps from `declare const Game: Game;` to `declare var Game: Game;`, this goes away. It seems as though the typings doesn't allow you to directly modify the Game object by declaring it as a constant rather than a var.

### Expected Behavior

Using `interface Game { ... }` in a separate declaration file should produce no issue, such as using `interface Creep { ... }`.

### Actual Behavior

Compiler sees Game as declared as a constant and gets mad if you try to modify the interface.

### Sample code (if available)

My declaration file: 
```ts
interface Game {
	cache: {
		assignments: { [ref: string]: { [roleName: string]: string[] } };
		targets: { [ref: string]: string[] };
		objectives: { [ref: string]: string[] };
		structures: { [roomName: string]: { [structureType: string]: Structure[] } };
		drops: { [roomName: string]: { [resourceType: string]: Resource[] } };
		constructionSites: { [roomName: string]: ConstructionSite[] };
	};
	icreeps: { [name: string]: ICreep };
	directives: { [name: string]: IDirective };
}
```

Screeps typings:
```ts 
interface Game {
    ...
}
declare const Game: Game;
```
### Your Environment

- Node.js version: 8
- TypeScript version: 2.6.1

**Comment by resir014** [comment]
This should be fixed in #29. Thanks for reporting!
