### ISSUE TITLE
store property not in Structure

### ISSUE THREAD

**Issue by tdamsma** [screepers/typed-screeps#30]
### Expected Behavior

I think the store property should be an optional field for a structure, as it is implemented by StructureContainer, and returned by calling a FIND_STRUCTURES. Now I am a bit new to typescript, so not completely sure what the desired behaviour should be

### Sample code

```ts
let target = creep.pos.findClosestByRange(FIND_STRUCTURES, {
            filter: (structure: Structure) => {
                return (structure.structureType == STRUCTURE_CONTAINER) 
                      && structure.store ? structure.store.energy < structure.storeCapacity : false;
            }
        });
```
The only way to get the above working for me is to put an any type in the function call: `structure: Structure` 

### Your Environment

- Node.js version: 8.9.3
- TypeScript version: 2.6.2

**Comment by apemanzilla** [comment]
What version of the definitions are you using? This should have been fixed by 87868384be6c8ac179f94940f4dfa0d99c562cac.

**Comment by tdamsma** [comment]
I must have been on an older version, thought I had updated but apparently not. Yarn and windows don't always play nice together.

However this still confuses me. I am trying to check energy stored vs capacity for both containers and the spawn. So I tries something like this:
``` ts
        let target = creep.pos.findClosestByRange(FIND_STRUCTURES, {
            filter: (structure: AnyStructure) => {
                return (
                    (structure.structureType == STRUCTURE_CONTAINER) ||
                    (structure.structureType == STRUCTURE_SPAWN)
                )
                    && structure.store ? structure.store.energy < structure.storeCapacity : false;
            }
        });
```
This yields the following error:
```
[ts]
Property 'store' does not exist on type 'StructureSpawn | StructureContainer'.
  Property 'store' does not exist on type 'StructureSpawn'.
```
Is this working as it should? As in, because StructureSpawn doesn't implement `store` I can't even test for it? However this does work, so maybe typescript is just smarter than I thought:

``` ts
        let target = creep.pos.findClosestByRange(FIND_STRUCTURES, {
            filter: (structure: AnyStructure) => {
                return (
                    (structure.structureType == STRUCTURE_SPAWN) ||
                    (structure.structureType == STRUCTURE_CONTAINER)
                )
                    && structure.structureType == STRUCTURE_CONTAINER ? structure.store.energy < structure.storeCapacity : 
                        structure.energy < structure.energyCapacity
                    ;
            }
        });
```

Is this really the correct way to implement this? It seems so verbose though

**Comment by apemanzilla** [comment]
TypeScript is a bit pedantic in that regard, you're supposed to use `"store" in structure` or similar.

What might be better is modifying the `StructureSpawn` prototype to have a `store` property that's created using the `energy` property.
