### ISSUE TITLE
Tombstone support is missing.

### ISSUE THREAD

**Issue by KageJittai** [screepers/typed-screeps#53]
LOOK_TOMBSTONE and other type definitions for tombstones are missing despite being in the game.

### Expected Behavior

Tombstone api changes should be in the latest version.

### Actual Behavior

Tombstone api changes are not in the latest version.

### Sample code (if available)

```ts
        let tombstone = creep.room.lookForAtArea(LOOK_TOMBSTONE, creep.pos.y - 2, creep.pos.x - 2, creep.pos.y + 2, creep.pos.x + 2, true);
```

### Your Environment

- Node.js version: v8.10.0
- TypeScript version: Version 2.7.2
- {`@types/screeps`} version: 2.2.0

**Comment by resir014** [comment]
This is in progress: #48.

**Comment by Arcath** [comment]
Now that #48 has been merged this will be released in the next version
