### ISSUE TITLE
withdraw not working with tombstones

### ISSUE THREAD

**Issue by Daxten** [screepers/typed-screeps#59]
Guess withdraw should look like this now?

    withdraw(target: Structure | Tombstone, resourceType: ResourceConstant, amount?: number): ScreepsReturnCode

**Comment by Daxten** [comment]
also Tombstone doesn't have the id property

**Comment by Arcath** [comment]
Sorry, missed that in #53.

I'll work on a fix as soon as I can.

**Comment by Arcath** [comment]
This was fixed in #60 and released in 2.3.0. You can use `typed-screeps` now or wait for this pr to be pulled before using `@types/screeps` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25086
