### ISSUE TITLE
dist version does not match src version

### ISSUE THREAD

**Issue by chobobobo** [screepers/typed-screeps#6]
I've re-discovered the issue with the second declaration of RoomPosition.getDirectionTo returning number instead of DirectionConstant.  While this seems to have been fixed in src, the version in dist does not reflect that change.

I was just following the instructions to install using typings, am I meant to compile them myself instead?

**Comment by bryanbecker** [comment]
Thanks for the heads up.  I forgot to check whether or not the previous PR included the compiled changes.

Should be fixed now
