### ISSUE TITLE
Cannot redeclare block-scoped variable `Game`

### ISSUE THREAD

**Issue by bencbartlett** [screepers/typed-screeps#61]
This is related to #26. The current version of typed-screeps declares `Game` with `let` instead of `var`, so extending the interface in other files throws TS2451. To fix it, change [line 81](https://github.com/screepers/typed-screeps/blob/master/src/game.ts#L81) from `declare let Game: Game;` to `declare var Game: Game;`.

### Your Environment

- Node.js version: 8
- TypeScript version: 2.7.2
- {`typed-screeps` or `@types/screeps` delete as appropriate} version: 2.2.2

**Comment by apemanzilla** [comment]
Do you have a specific example of this? I have no issues using interface merging:

```typescript
interface Game {
	myProperty: boolean;
}

console.log(Game.myProperty);

```

**Comment by bencbartlett** [comment]
The problem is reproducible when using another set of typings that also declares Game. I use `screeps-profiler` and `@types/screeps-profiler`. Relevant code portions are given below:

```ts
// typed-screeps:
interface Game {
    ...
}
declare let Game: Game; // works if let is replaced with var
```

```ts
// @types/screeps-profiler:
declare global {
    interface Game {
        profiler: ScreepsGameProfiler;
    }
    var Game: Game;
}
```

```ts
// Overmind: index.d.ts
interface Game {
	zerg: { [name: string]: any };
	directives: { [name: string]: any };
}
```

Switching both declarations to `let` does not fix the problem, only `var` properly declares `Game` in a way that allows other modules to redeclare and extend it.

**Comment by apemanzilla** [comment]
IMO `@types/screeps-profiler` shouldn't be redeclaring `Game` in the first place and should instead have a peer dependency on `typed-screeps` or another set of screeps typings, but I've merged the PR.

**Comment by bencbartlett** [comment]
I agree, but it's also probably best to declare `Game` in the most compatible manner possible even if it is slightly less ES6-ish.
