### ISSUE TITLE
Lack of coding style

### ISSUE THREAD

**Issue by Jomik** [screepers/typed-screeps#89]
There seems to be a lack of coding style for the code base here.
Some long lines are broken, some are not.
Some files use 2 space indentation, some use 4.
Thus I had no clue what to do in #88 😂

**Comment by apemanzilla** [comment]
You should follow the [editorconfig](https://github.com/screepers/typed-screeps/blob/master/.editorconfig) where applicable (indents, line endings, etc). As for line length, I don't think we ever decided to use a specific style for that, especially considering how long some of the signatures can be.

**Comment by Jomik** [comment]
Yes, I am aware. But I don't want to commit formatting changes to your code base in a feature PR. Also seems a bit much to add a PR just to fix fomatting :)
https://github.com/screepers/typed-screeps/blob/master/src/literals.ts
Would be nice to have a decision on those things so that prettier/tslint can be set to adhere to them. Currently when I save a file, I'll get scattered changes because my linter settings breaks long lines.

**Comment by resir014** [comment]
@Jomik I can include Prettier after I've finished sifting through the PRs.

**Comment by Jomik** [comment]
Awesome! :)
