### ISSUE TITLE
Replace uses of any with unknown

### ISSUE THREAD

**Issue by dmarcuse** [screepers/typed-screeps#93]
`unknown` offers greater type safety, even without knowing exact type information. Replacing `any` with `unknown` - e.g. for return values of `Game.getObjectById(id: string)` - would help catch errors by requiring type guards, or at least explicit casts. This specific example would work particularly well in conjunction with #92.

**Comment by pyrodogg** [comment]
This has been implemented by #144 (and other PRs) to change default return type of `Game.getObjectById` to `unknown` if provided a `string` type id, which is deprecated as of 3.0. Users should now use typed Ids to retrieve game objects.
